### ISSUE TITLE
Can't start after install

### ISSUE THREAD

**Issue by oren-ned** [alilajevardi/MapVisual4pbi#1]
Hi There,
Not sure what is the issue and cant start the app after installation. If you can please provide some suggestions that would be great.
Cheers,
N.

![image](https://user-images.githubusercontent.com/10034654/192079467-65bf1e76-cdc6-4a18-afb4-1de02a08486b.png)

**Comment by alilajevardi** [comment]
Hi Ned,
I think there is a problem with path in your added image. You need to complete the step 3 of setup instructions in the code directory ---> \MapVisual4pbi
Then run "pbiviz package"
Please let me know if it solve the problem.
Regards,
A

**Comment by alilajevardi** [comment]
> Hi There, Not sure what is the issue and cant start the app after installation. If you can please provide some suggestions that would be great. Cheers, N.
> 
> ![image](https://user-images.githubusercontent.com/10034654/192079467-65bf1e76-cdc6-4a18-afb4-1de02a08486b.png)


Hi Ned,
I think there is a problem with path in your added image. You need to complete the step 3 of setup instructions in the code directory ---> \MapVisual4pbi
Then run "pbiviz package"
Please let me know if it solve the problem.
Regards,
A

**Comment by oren-ned** [comment]
Hi Alireza,

I followed the steps and captured the screen grabs.  The third an forth screen captures shows the result of comments "pbiviz start" and "pbiviz package" respectively.

I also tried to download the code and run "npm install" and run the "pbiviz start" and "pbiviz package" and result didn't change.

Regards,
Nedim

![image](https://user-images.githubusercontent.com/10034654/192113749-0beb444a-dbeb-4f05-8923-df96cc47b5e9.png)
![image](https://user-images.githubusercontent.com/10034654/192113762-3c77770c-accf-4429-8651-84ec5eabf17c.png)
![image](https://user-images.githubusercontent.com/10034654/192113977-5f14e6bd-abab-436f-a76c-7a4dd31511dd.png)
![image](https://user-images.githubusercontent.com/10034654/192114155-7f861205-b488-4bfb-aaec-75703dd29330.png)

**Comment by oren-ned** [comment]
Hi Alireza,

I was able to get it working by simply deleting the excising "visual.ts" file and re-creating it by simply copying the content from the old file to the new file. 

Still not sure what is the issue with the original "visual.ts" file.

Thank you for the help and will keep you posted after reviewing the project.

Regards,
Nedim
